# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
### Environment for xdg-desktop-portal-hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE

### Setup Quickshell
exec-once = QT_NO_XDG_DESKTOP_PORTAL=1 qs -d &
exec-once = QT_NO_XDG_DESKTOP_PORTAL=1 qs -c ~/.config/quickshell/overview -d &
exec-once = QT_NO_XDG_DESKTOP_PORTAL=1 qs -c ~/.config/quickshell/launcher -d &
exec-once = QT_NO_XDG_DESKTOP_PORTAL=1 qs -c ~/.config/quickshell/gamelauncher -d &
exec-once = ~/.config/hypr/scripts/quickshell/tray/trayctl.sh watch &
exec-once = python3 ~/.config/hypr/scripts/quickshell/archtools/focus_daemon.py
exec-once = python3 ~/.config/hypr/scripts/quickshell/archtools/arch-news.py --fetch
exec-once = python3 ~/.config/hypr/scripts/quickshell/archtools/dotfiles-updates.py
exec-once = ~/.config/hypr/scripts/enable-kde-filechooser-runtime.sh 20 &

### Load Wallpaper
exec-once = awww-daemon

### Hypridle
exec-once = hypridle

## Hyprsunset
exec-once = hyprsunset

### Load cliphist history
exec-once = wl-paste --watch cliphist store

### Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1

### Kwallet
exec-once = ~/.config/hypr/scripts/start-kwallet.sh

### Soundboard
exec = ~/.config/hypr/scripts/soundboard.sh

# AutoRun Apps
exec-once = kdeconnect-indicator &
exec-once = solaar --window=hide &
exec-once = ~/.config/hypr/scripts/quickshell/tray/trayctl.sh launch 30 'flatpak run com.core447.StreamController -b' &
exec-once = steam --window=hide &
exec-once = easyeffects --hide-window &
exec-once = localsend --hidden &
exec-once = sunshine &
exec-once = [workspace 2; silent] sleep 2 && vivaldi
exec-once = sh -c 'sleep 6 && ~/.config/hypr/scripts/quickshell/tray/trayctl.sh launch 30 vesktop' &
exec-once = ~/.config/hypr/scripts/quickshell/tray/trayctl.sh launch 30 element-desktop &
