# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
### Setup Quickshell
exec-once = qs -d &
exec-once = qs -c ~/.config/quickshell/overview -d &
exec-once = qs -c ~/.config/quickshell/launcher -d &
exec-once = qs -c ~/.config/quickshell/gamelauncher -d &
exec-once = python3 ~/.config/hypr/scripts/quickshell/archtools/focus_daemon.py

### Load Wallpaper
exec-once = awww-daemon

### Hypridle
exec-once = hypridle

## Hyprsunset
exec-once = hyprsunset

### Load cliphist history
exec-once = wl-paste --watch cliphist store

### Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# AutoRun Apps
exec-once = kdeconnect-indicator &
exec-once = solaar --window=hide &
exec-once = flatpak run com.core447.StreamController -b &
exec-once = steam --window=hide &
exec-once = easyeffects --hide-window &
exec-once = localsend --hidden &
exec-once = sunshine &
exec-once = [workspace 2; silent] vivaldi
exec-once = sh -c 'sleep 6 && vesktop' &
exec-once = element-desktop &

