# -----------------------------------------------------
# Window Rules
# -----------------------------------------------------
## hyprctl clients to get titles and class
## hyprctl layers to get layers address

windowrule = float on, match:title ^(.*All Files*.)$
windowrule = opacity 1.2, match:title Typst Preview — Mozilla Firefox


# Browser Picture in Picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = move 69.5% 4%, match:title ^(Picture-in-Picture)$

# idleinhibit
windowrule = idle_inhibit fullscreen, match:class ([window])   # modes: none, always, focus, fullscreen

# workspaces
windowrule = workspace 3 silent, match:title ^(.*Discord.*)$
windowrule = workspace 4 silent, match:title ^(.*Steam.*)$
windowrule = workspace 4, tile on, match:class ^(.*Spotify.*)$
windowrule = workspace 4, tile on, match:class ^(.*feishin.*)$
windowrule = workspace 1, match:title ^(.*Steam\sBig\sPicture\sMode.*)$
windowrule = workspace 3, tile on, match:class ^(.*Element.*)$

