# -----------------------------------------------------
# Misc
# -----------------------------------------------------
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    initial_workspace_tracking = 1
    animate_mouse_windowdragging = true
    focus_on_activate = true
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}

