# -----------------------------------------------------
# Monitor
# -----------------------------------------------------
monitor=DP-2,2560x1440@239.972,0x480,1
monitor=DP-1,1920x1080@143.855,2560x0,1,transform,3
