# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
### Setup Quickshell
exec-once = qs -d &
exec-once = qs -c ~/.config/quickshell/overview -d &
exec-once = qs -c ~/.config/quickshell/launcher -d &
exec-once = qs -c ~/.config/quickshell/gamelauncher -d &
exec-once = python3 ~/.config/hypr/scripts/quickshell/archtools/focus_daemon.py
exec-once = python3 ~/.config/hypr/scripts/quickshell/archtools/arch-news.py --fetch
exec-once = python3 ~/.config/hypr/scripts/quickshell/archtools/dotfiles-updates.py

### Load Wallpaper
exec-once = awww-daemon &

### Hypridle
exec-once = hypridle &

## Hyprsunset
exec-once = hyprsunset

### Load cliphist history
exec-once = wl-paste --watch cliphist store &

### Polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &

### Kwallet
exec-once = ~/.config/hypr/scripts/start-kwallet.sh

### Auto dimmer brightness
exec-once = pgrep -f brightness_auto_power.sh >/dev/null || bash ~/.config/hypr/scripts/quickshell/brightness/brightness_auto_power.sh

### Environment for xdg-desktop-portal-hyprland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# AutoRun Apps
exec-once = kdeconnect-indicator &
exec-once = localsend --hidden &

