# -----------------------------------------------------
# Window Rules
# -----------------------------------------------------
## hyprctl clients to get titles and class
## hyprctl layers to get layers address

windowrule = float on, match:title ^(.*Open Files*.)$
windowrule = opacity 1.3 , match:title Typst Preview — Mozilla Firefox

# Browser Picture in Picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$
windowrule = move 69.5% 4%, match:title ^(Picture-in-Picture)$

# idleinhibit
windowrule = idle_inhibit fullscreen, match:class ([window])   # modes: none, always, focus, fullscreen
