[preferred]
default=hyprland;gtk;kde
org.freedesktop.impl.portal.Settings=gtk
org.freedesktop.impl.portal.OpenURI=kde
org.freedesktop.impl.portal.FileChooser=kde
org.freedesktop.impl.portal.AppChooser=kde
