general {
    before_sleep_cmd = /home/corradoenea/.config/hypr/scripts/quickshell/lock/lock_screen.sh
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
}

listener {
    timeout = 300
    on-timeout = /home/corradoenea/.config/hypr/scripts/quickshell/lock/lock_screen.sh
    ignore_inhibit = false
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
    ignore_inhibit = false
}
