cursor_shape beam
cursor_shape_unfocused unchanged
cursor_trail 2

background_opacity 0.5

font_family Nimbus Mono PS
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10

symbol_map U+E000-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono

shell zsh

include ~/.config/kitty/colors.conf
