#!/usr/bin/env bash

dbus-update-activation-environment --systemd \
  DISPLAY \
  WAYLAND_DISPLAY \
  XDG_CURRENT_DESKTOP \
  XDG_SESSION_DESKTOP \
  XDG_SESSION_TYPE \
  DESKTOP_SESSION \
  DBUS_SESSION_BUS_ADDRESS

systemctl --user import-environment \
  DISPLAY \
  WAYLAND_DISPLAY \
  XDG_CURRENT_DESKTOP \
  XDG_SESSION_DESKTOP \
  XDG_SESSION_TYPE \
  DESKTOP_SESSION \
  DBUS_SESSION_BUS_ADDRESS

sleep 2

/usr/lib/pam_kwallet_init >/tmp/pam_kwallet_init.log 2>&1
